trigger:
- master
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd terraform
    az login
    terraform init
    terraform apply -auto-approve
  displayName: 'Applying Azure Policy'
